<main class="content">
    <h1>Vores historie</h1>
    <p>Der var engang...sådan starter som bekendt mange eventyr og Cykelfærgens historie minder lidt om et eventyr. Fra middelalderen og frem til 1874 sejlede der op til 3 færger mellem Brunsnæs (DK) og Holnis (DE).</p>
    <p>Borgere på hhv Broagerland og på tysk side har de seneste 30 år skiftevis forsøgt at genoplive drømmen om færgesejlads på Flensborg Fjord, uden dog at kunne trænge helt igennem med deres projekt.</p>
    <p>BIB Landsbylaug påtog sig opgaven tilbage i 2016, og fik sammensat et stærkt hold af lokale ildsjæle, kompetente støtter fra kommunalt regie, krydret med ekspertviden indenfor turisme og det maritime. Med offentlige midler på 200.000 kr blev der udarbejdet en professionel forretningsplan på dansk og tysk, som et enigt byråd i Sønderborg Kommune godkendte.</p>
    <p>Sideløbende blev der knyttet konstruktive kontakter til politikker i Folketinget, på byrådsplan i både Danmark og Tyskland idet Flensborg Fjord betragtes som internationalt farvand, med dengang forskellige opfattelser af lovgivningen. En harmonisering af lovgivningen mellem Danmark og Tyskland betød herefter, at projektgruppen kunne koncentrere sig om at indgå aftaler med den danske Søfartsstyrelse alene.</p>
    <p>Dernæst blev der etableret aftaler med forskellige havne på dansk og tysk side, troede vi. Langballigau som den foretrukne tyske havn, idet Holnis pga lavvande og fredning ikke kunne realiseres, trak sig fra aftalen og vi stod lige pludselig helt uden tysk havn. Igen blev der brug for diplomati, medierne blev bragt i spil og mange borgere i grænselandet på dansk og tysk side meldte sig på banen og gav udtryk for deres utilfredshed. En ny borgmester i Langballig blev valgt og besøgte umiddelbart derefter projektlederen for Cykelfærgen hjemme på hans terrasse i Brunsnæs. Et lille topmøde med vidtrækkende konsekvenser, idet det hurtigt gik op for vores tyske venner, at de var blevet fejlinformeret og deres afvisning blev ændret til 100% opbakning.</p>
    <p>Elephanten fra Hadsund melder sig på banen, hvor kaptajn Erik Bertelsen har sejlet som Cykelfærge mellem Dragør (DK) og Sverige tilbage i 2017, men efter blot 1 år måtte projektet lukke ned igen og nu vil stille sit skib og mandskab til rådighed på Flensborg Fjord. Vi nåede langt i vores forsøg på en aftale med Elephanten, som endda har sejlet med den danske kongefamilie. Ændringer i dybdeforholdene i Brunsnæs henover vinteren i 2018/2019 gjorde dette til en umulighed, og vi måtte desværre takke nej til Erik.</p>
    <p>Hurtigt fik vi et tip om, at der lå et skib i Mommark, som evt kunne bruges. Vi besøgte Palle Heinrich og besigtigede skibet Rødsand i januar 2019 og gik omgående i arbejdstøjet for at få tilladelser mm på plads. Målet var, at vi skulle starte sejladsen i juni måned 2019, men det blev igen en hård kamp med myndigheder og styrelser, som dog endte som i et eventyr med, at vi kunne omfavne hinanden og sende Cykelfærgen på sin første sejlads....og tænk, vi blev de første dage ledsaget af en delfin.</p>
    <p>2020 skulle succesen fra 2019 gentages, men her kom Corona i vejen, og vi måtte sadle om igen. Der kunne ikke sejles til Tyskland og Sønderhav (DK) blev derfor valgt som alternativ, med en lidt kortere sæson end den oprindelig planlagte.</p>
    <p>I 2021 har vi igen kæmpet med Corona, men omkring 1. Maj begyndte tingene at gå vores vej og vi turde at melde ud om, at vi igen ville tilbyde rutesejlads til Tyskland, som starter fredag den 25. Juni.</p>
    <p>Vi er glade og stolte over det vi har opnået, nemlig med frivillige kræfter at skabe en grænseoverskridende sejlads, hvor vi anlægger i alt 4 danske havne og 2 tyske havne. Dernæst mulighed for at booke skibet til 3 timers eventsejlads.</p>
    <p>Eventyret slutter ikke her. Det er først lige begyndt.
    <br>
    Projektleder for Cykelfærgen på Flensborg Fjord<br>
    Gerhard Jacobsen
    </p>
</main>